Align action configs with legacy ones to allow LtoBackend actions to succeed
Copybara Import from https://github.com/bazelbuild/rules_cc/pull/528

BEGIN_PUBLIC
Align action configs with legacy ones to allow LtoBackend actions to succeed (#528)

This matches how it was previously setup: https://github.com/bazelbuild/rules_cc/blob/933844609a1c1f0ea0ddb64c28d463e901f36f57/cc/private/toolchain_config/legacy_features.bzl#L169-L187

Without this, we get:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.AssertionError: LtoBackendAction command line expansion cannot fail
	at com.google.devtools.build.lib.rules.cpp.LtoBackendAction.computeKey(LtoBackendAction.java:288)
	at com.google.devtools.build.lib.actions.ActionKeyComputer.getKey(ActionKeyComputer.java:43)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:575)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:764)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:706)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:345)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:202)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:471)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.google.devtools.build.lib.actions.CommandLineExpansionException: Invalid toolchain configuration: Cannot find variable named 'preprocessor_defines'.
	at com.google.devtools.build.lib.rules.cpp.LtoBackendArtifacts$1.arguments(LtoBackendArtifacts.java:129)
	at com.google.devtools.build.lib.rules.cpp.LtoBackendArtifacts$1.arguments(LtoBackendArtifacts.java:109)
	at com.google.devtools.build.lib.actions.CommandLines.allArguments(CommandLines.java:171)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.getArguments(SpawnAction.java:208)
	at com.google.devtools.build.lib.rules.cpp.LtoBackendAction.computeKey(LtoBackendAction.java:286)
```

I now have this fully working e2e at https://github.com/cerisier/toolchains_llvm_bootstrapped/pull/56/files#diff-cce4f0083471dff12279a3b4e3b3206404e4932a3d60f3443c0f60900706093e so happy to contribute those feature targets as well if someone tells me where to put them :)

Closes #528
END_PUBLIC

COPYBARA_INTEGRATE_REVIEW=https://github.com/bazelbuild/rules_cc/pull/528 from dzbarsky:zbarsky/fix-lto 505202d995075b2d786760e41adccf5e7d2771ea
PiperOrigin-RevId: 835974414
Change-Id: Idc2c40ec66a48e679417edaddf545b889d717fc2