Fix make variable handling in rule-based toolchain example
Copybara Import from https://github.com/bazelbuild/rules_cc/pull/398

BEGIN_PUBLIC
Fix make variable handling in rule-based toolchain example (#398)

This fixes the following error in the gcc-rule-based toolchain example introduced by the recent "Add cc_make_variable" patch.
```
ERROR: /home/mlaurin/src/bazel/rules_cc.git/examples/rule_based_toolchain/static_answer/BUILD.bazel:19:11: in cc_library rule //static_answer:answer:
Traceback (most recent call last):
File "/virtual_builtins_bzl/common/cc/cc_library.bzl", line 58, column 49, in _cc_library_impl
File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 926, column 64, in _get_copts
File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 911, column 37, in _expand_make_variables_for_copts
File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 819, column 46, in _expand
File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 765, column 26, in _expand_nested_variable
File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 719, column 9, in _lookup_var
Error in fail: @@//static_answer:answer: $(EXAMPLE_SUBSTITUTION) not defined
ERROR: /home/mlaurin/src/bazel/rules_cc.git/examples/rule_based_toolchain/static_answer/BUILD.bazel:19:11: Analysis of target '//static_answer:answer' failed
ERROR: Analysis of target '//static_answer:answer' failed; build aborted
INFO: Elapsed time: 0.239s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: No test targets were found, yet testing was requested
```

There was a mention of this defect in issue #395.

Closes #398
END_PUBLIC

COPYBARA_INTEGRATE_REVIEW=https://github.com/bazelbuild/rules_cc/pull/398 from Synss:fixup-gcc-make_variables-handling bc44b99ebac9947bb7fe7bd73f6801d91db78083
PiperOrigin-RevId: 747468867
Change-Id: I175d6b8bf59ae21ba4a3f809f0a1decc3ae662fd