Pass fission flags to ThinLTO backend actions (#837)
Fix interaction between `--fission` and `--features=thin_lto`. Without this, every LTO backend action fails:

```
ERROR: output 'prog.lto/bazel-out/k8-opt/bin/_objs/prog/a.dwo' was not created
ERROR: LTO Backend Compile prog.lto/bazel-out/k8-opt/bin/_objs/prog/a.o failed:
       not all outputs were created or valid
```

Fixed by adding `ACTION_NAMES.lto_backend` to the `per_object_debug_info` flag_set in
`cc/private/toolchain/unix_cc_toolchain_config.bzl` and `cc/private/toolchain_config/legacy_features.bzl`.

Adds a test that uses the real Linux `cc_toolchain_config` since that wasn't covered by the existing test, and was broken.

Closes #837

COPYBARA_INTEGRATE_REVIEW=https://github.com/bazelbuild/rules_cc/pull/837 from akonradi:abakon/fission-flags-for-lto-backend c033aba8813345a9c84a3f48cf11fb9bf970774d
PiperOrigin-RevId: 964562193
Change-Id: I09f0c92967f5d148dfa24edca0533e306a2647bb