[toolchain] Mark some more variables as optional
All of these are used with `expand_if_{,not_}available` in `unix_cc_toolchain_config.bzl` and I've seen failures with unconditionally expanding `source_file` in some cases in our internal build.

```
ERROR: /.../external/rules_go+/BUILD.bazel:88:17: in cgo_context_data rule @@rules_go+//:cgo_context_data:
Traceback (most recent call last):
        File "/.../external/rules_go+/go/private/context.bzl", line 737, column 54, in _cgo_context_data_impl
                cc_common.get_memory_inefficient_command_line(
        File "/virtual_builtins_bzl/common/cc/cc_common.bzl", line 205, column 66, in _get_memory_inefficient_command_line
Error in get_memory_inefficient_command_line: Invalid toolchain configuration: Cannot find variable named 'source_file'.
ERROR: /.../external/rules_go+/BUILD.bazel:88:17: Analysis of target '@@rules_go+//:cgo_context_data' failed
```