Fix clang version parsing on Windows.
Copybara Import from https://github.com/bazelbuild/rules_cc/pull/626

BEGIN_PUBLIC
Fix clang version parsing on Windows. (#626)

The official Windows release of Clang 22 changed the output format of `-v`.
```
$ clang -v
clang version 22.1.1 (https://github.com/llvm/llvm-project fef02d48c08db859ef83f84232ed78bd9d1c323a)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

This makes version parsing fail, and in turn leads to failed compilation for basically any C++ code as the version is used for `cxx_builtin_include_directories`. Without the change in this PR, I get
```
cxx_builtin_include_directories = [
    ...
    "C:\\Program Files\\LLVM\\lib\\clang\\fef02d48c08db859ef83f84232ed78bd9d1c323a)\\include"
],
```
instead of `"C:\\Program Files\\LLVM\\lib\\clang\\22\\include"` in the autoconfigured toolchain.

Compiling
```cc
#include <iostream>
int main() { return 0; }
```

then fails with:

```
ERROR: C:/users/jan/code/rules_cc_clang_cl_llvm22_repro/BUILD:3:8: Compiling main.cc failed: absolute path inclusion(s) found in rule '//:test':
the source file 'main.cc' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
  'C:/Program Files/LLVM/lib/clang/22/include/yvals_core.h'
  'C:/Program Files/LLVM/lib/clang/22/include/vadefs.h'
  'C:/Program Files/LLVM/lib/clang/22/include/yvals_core.h'
...
```

I didn't find any tests for this or any easy way of adding them but please let me know if I missed something.

Closes #626
END_PUBLIC

COPYBARA_INTEGRATE_REVIEW=https://github.com/bazelbuild/rules_cc/pull/626 from polasek:jan/fix-clang-version-parsing 1d06c3888b4bbb138d5737d787cc61d891984747
PiperOrigin-RevId: 886412725
Change-Id: If09ff4ef0d1181846d3b722f2fec03a75e999876